
class GExtraData
{
public:
	enum
	{
		EXTRA_POSITION_DATA,
		EXTRA_INT_DATA,
		EXTRA_DATA_MAX,
	};
	enum eExtraType
	{
		EXTRA_DAMAGE_POSITION,
		EXTRA_SHADOW_POSITION,
		EXTRA_GAGE_POSITION,
		EXTRA_MISSILEDAMAGE_POSITION,
		EXTRA_FARATTACK_POSITION,
		EXTRA_HEROFIRE_POSITION,
		EXTRA_HEROWALL_POSITION,
	};
};