// GnTools.idl : GnTools.exe에 대한 형식 라이브러리 소스

// 이 파일은 MIDL 컴파일러에 의해 처리되어
// 형식 라이브러리(GnTools.tlb)를 생성합니다.

#include "olectl.h"
[ uuid(1648CA1B-1D6E-43DB-8E3B-DFB5C4FBED64), version(1.0) ]
library GnTools
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CGnToolsDoc의 기본 디스패치 인터페이스
	
	[ uuid(825D5E62-11AB-4FC9-AF78-13E954238533) ]
	dispinterface IGnTools
	{
		properties:
			
		methods:
	};

	//  CGnToolsDoc의 클래스 정보
	
	[ uuid(40AEC219-DA5A-42B0-81C1-7F7BD24BC0B2) ]
	coclass CGnToolsDoc
	{
		[default] dispinterface IGnTools;
	};
	//  GtFloatSpinButtonCtrl의 기본 디스패치 인터페이스입니다.
		
	[ uuid(CC38B162-DEED-411B-AA0A-6D2D44AF24F2) ]
	dispinterface IGtFloatSpinButtonCtrl
	{
		properties:
		methods:
	};

	//  GtFloatSpinButtonCtrl의 클래스 정보입니다.

	[ uuid(8C4187D0-1070-4C85-BFE6-0A7634DF7EF4) ]
	coclass GtFloatSpinButtonCtrl
	{
		[default] dispinterface IGtFloatSpinButtonCtrl;
	};
};
